### ISSUE TITLE
[META] Upgrade Testing Framework Issue List

### ISSUE THREAD

**Issue by chelma** [opensearch-project/opensearch-migrations#10]
Meta issue to track the work associated with the Upgrade Testing Framework.

Framework Workstream
- [x] https://github.com/opensearch-project/opensearch-migrations/issues/1
- [x] https://github.com/opensearch-project/opensearch-migrations/issues/4
- [x] https://github.com/opensearch-project/opensearch-migrations/issues/6
- [x] https://github.com/opensearch-project/opensearch-migrations/issues/8
- [x] https://github.com/opensearch-project/opensearch-migrations/issues/7
- [x] https://github.com/opensearch-project/opensearch-migrations/issues/50
- [ ] https://github.com/opensearch-project/opensearch-migrations/issues/51
- [ ] https://github.com/opensearch-project/opensearch-migrations/issues/65

Expectations Workstream
- [x] https://github.com/opensearch-project/opensearch-migrations/issues/2
- [x] https://github.com/opensearch-project/opensearch-migrations/issues/3
- [ ] https://github.com/opensearch-project/opensearch-migrations/issues/5

Miscellaneous
- [x] https://github.com/opensearch-project/opensearch-migrations/issues/14
- [x] https://github.com/opensearch-project/opensearch-migrations/issues/48
- [x] https://github.com/opensearch-project/opensearch-migrations/issues/49

**Comment by chelma** [comment]
From community demo of the UTF today - this tool exists and may be worth exploring and/or collaborating with its developers on.

https://github.com/smortex/es-to-os
