### ISSUE TITLE
[Meta] Enable multi-hop migration of data through snapshot-restore

### ISSUE THREAD

**Issue by kartg** [opensearch-project/opensearch-migrations#23]
This meta issue tracks feature work that enables customers to migrate their data from a cluster running on a legacy version to the latest version of OpenSearch, through the snapshot-restore mechanism.

- [x] Enable searchable snapshot support for older versions (ES 6.0) - https://github.com/opensearch-project/OpenSearch/issues/5451
- [ ] ~Expand the above functionality to support even older versions (say ES 5.0)~
- [ ] ~Investigate re-indexing of old snapshots on the updated cluster~

This method could also be used for upgrading clusters in-place, but would result in downtime

**Comment by setiah** [comment]
While snapshot restore is great option for lift-and-shift migrations, it would be exciting to see this functionality expanded to in-place upgrades as well as it provides zero downtime option for version migrations. Could we also track that as part of Multi-version meta issue?

**Comment by kartg** [comment]
Related - https://github.com/opensearch-project/OpenSearch/issues/5443

**Comment by kartg** [comment]
Ownership of the extended compatibility of searchable snapshots has been moved to the core `opensearch` repo - https://github.com/opensearch-project/OpenSearch/issues/5948

We will revisit reindexing of snapshots at a later time. Closing the issue.
